# This file was generated by GoReleaser. DO NOT EDIT.
cask "coffer" do
  name "coffer"
  desc "CLI tool for managing application configuration with GCP Secret Manager integration"
  homepage "https://github.com/sultano/coffer"
  version "0.12.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coffer"

  on_macos do
    on_intel do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_darwin_amd64.tar.gz"
      sha256 "4ce0a47e60a94cda8a7690c38351283990585fa407a47482380d8c38fd1615a6"
    end
    on_arm do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_darwin_arm64.tar.gz"
      sha256 "16fe4a0bde8731b1590840a271064c9df3937a3417d402122f7d147659090b3c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_linux_amd64.tar.gz"
      sha256 "879f03c92ea81fd624e044caa74326dbd7c92e26ed07a74d450adeb20c87770d"
    end
    on_arm do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_linux_arm64.tar.gz"
      sha256 "1bb9b47616378ad6a8dd02f6e3339da7a095ab94890bcccf2c234caeb16a34b6"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coffer"]
    end
  end

  # No zap stanza required
end
