# This file was generated by GoReleaser. DO NOT EDIT.
cask "coffer" do
  name "coffer"
  desc "CLI tool for managing application configuration with GCP Secret Manager integration"
  homepage "https://github.com/sultano/coffer"
  version "0.10.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coffer"

  on_macos do
    on_intel do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_darwin_amd64.tar.gz"
      sha256 "515a2621595e056093c3c95d303bd58cae1361549607e2972a669fd9c5984fe7"
    end
    on_arm do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_darwin_arm64.tar.gz"
      sha256 "ec3123a9d7e8392e51ec5348ef2993a4ce2aafde5cdae80303dc6e1e380454fb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_linux_amd64.tar.gz"
      sha256 "6854b7846da96dfd3d5d740d1379b39d6c8ffbdfca1956382ceb86c49958a7b1"
    end
    on_arm do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_linux_arm64.tar.gz"
      sha256 "1f1cfdd72155e67a9d35439de0c733ae0722ad93ee5c463dbb03c379f897e8bf"
    end
  end

  # No zap stanza required
end
