# This file was generated by GoReleaser. DO NOT EDIT.
cask "coffer" do
  name "coffer"
  desc "CLI tool for managing application configuration with GCP Secret Manager integration"
  homepage "https://github.com/sultano/coffer"
  version "0.11.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "coffer"

  on_macos do
    on_intel do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_darwin_amd64.tar.gz"
      sha256 "b5288a04cf34f851d3fad578dd846f916f56e662edd68d72add73c900a1cded9"
    end
    on_arm do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_darwin_arm64.tar.gz"
      sha256 "5ca09869919ef64a9ba0bba8f608b8b08c2f77851554cf419271aecaa14cc062"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_linux_amd64.tar.gz"
      sha256 "a4bb31aad218500994558b368895ff5b0ce8850acc9bab09daed194da143441f"
    end
    on_arm do
      url "https://github.com/sultano/coffer/releases/download/v#{version}/coffer_#{version}_linux_arm64.tar.gz"
      sha256 "96588f2e8fed8190dbb2a56408708cbc80fef8d6f27d6b76fc9f86a733a9f5b3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/coffer"]
    end
  end

  # No zap stanza required
end
